
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true

rabbit:
  queue:
    name: queueName

  exchange: exchange

  routing:
    key: routing_key
server:
  port: 8082